SCREEN_SIZE = (600, 600)
MAX_STEP_X = (SCREEN_SIZE[0]/2)-20
MAX_STEP_Y = (SCREEN_SIZE[1]/2)-20

HEAD_MAX_X = SCREEN_SIZE[0]/2
HEAD_MAX_Y = SCREEN_SIZE[1]/2

UP = 'w'
DOWN = 's'
LEFT = 'a'
RIGHT = 'd'


# print(MAX_STEP_Y)